sudo: required
services: 
  - docker

before_install:
  - docker build -t megahdj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true megahdj/docker-react npm run test

deploy: 
  provider: azure_web_apps
  username: traviscideploy
  password: TravisDeployPasswordSecret88
  site: megahdj-docker-react  

language: generic  