sudo: required
services: 
  - docker

before_install:
  - docker build -t megahdj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true megahdj/docker-react npm run test

deploy: 
  provider: azure_web_apps
  username: megahdj-docker-react
  password: AW4DBiBR1nuYXpZWhK318vDoorBgoell8hDllqWTrnCoqMvqQtFaoa7dERzE
  site: http://megahdj-docker-react.azurewebsites.net  

language: generic  
